version: "3.8"
services:
  all-in-one:
    build:
      context: ./
      target: deployment
    volumes:
      - .:/build:delegated
      - ./log:/service/log:delegated
    ports:
      - 8080:8080
      - 8081:8081
  xlike:
    build:
      context: ./
      target: deployment_xlike
    ports:
      - 8081:8081
  annotator:
    build:
      context: ./
      target: deployment_annotator
    ports:
      - 8081:8081
